config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do  #NO ID access
      get "login"
      post "validate_login"
      delete "logout"
    end
    member do  # ID access

    end
  end

  root 'users#login'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, :confirm_password, presence: true, length: {maximum: 15, minimum: 4}
  validates :phone, presence: true, uniqueness: true, length: {maximum: 10, minimum: 10}, numericality: true

  def self.authenticate(email,password)
    @user=User.where(email: email, password: Digest::MD5.hexdigest(password)).last
    if not @user.blank?
      @user
    else
      nil
    end
  end

  before_save :encrypt_password
  def encrypt_password
    self.password = Digest::MD5.hexdigest(password)
    self.confirm_password = Digest::MD5.hexdigest(confirm_password)
  end

  after_validation :compare_password
  def compare_password
    if password != confirm_password
        errors.add(:base, "password and confirm_password do not match")
    end
  end

  before_destroy :take_backup
  def take_backup
    File.open("#{Rails.root}/public/#{self.id}.json","w"){|foo| foo.write(self.to_json)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   before_action :session_verify

   def session_verify
     if session[:user_id].blank?
       render login_users_path
     end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :session_verify, only: [:login, :validate_login, :new, :create]

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      redirect_to :action => "index"
    else
      render "new"
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update(user_params)
      redirect_to :action => "index"
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to :action => "index"
  end

  def show
    @user = User.find params[:id]
  end

  def validate_login
    @user = User.authenticate(params[:email], params[:password])
    if not @user.blank?
      session[:user_id] = @user.id
      redirect_to :action => "index"
    else
      flash[:notice] = "Email or password is incorrect"
      render "login"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_users_path
  end

  private

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def disp_active_user
    user = User.find session[:user_id]
    user.email
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MorningEstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Morning E_Store</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="/users">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if session[:user_id].blank? %>
          <li><a href="/users/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/users/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <%else%>
           <li><a><%= "Logged in as #{disp_active_user}"%></a></li>
        <%end%>
        <li><%= link_to 'Logout', logout_users_path, method: :delete if session[:user_id].present? %></li>
      </ul>
    </div>
  </nav>

<% flash.each do |key, value| %>
  <%=value%>
<%end%>

<%= yield %>

</body>
</html>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <% @user.errors.messages.each do |msg|%>
    <%=msg%>
  <%end%>
<%end%>

app/views/users/edit.html.erb
<%= form_for @user do | f |%>
<table class='table table-striped'>
  <tr>
    <td><%= f.label :name%></td>
    <td><%= f.text_field :name%></td>
  </tr>
  <tr>
    <td><%= f.label :email%></td>
    <td><%= f.email_field :email%></td>
  </tr>
  <tr>
    <td><%= f.label :phone%></td>
    <td><%= f.text_field :phone%></td>
  </tr>
  <tr>
  <td><%= f.submit%></td>
</tr>
</table>
<%end%>
<%= link_to "Go Back", users_path,:class=>'btn btn-primary'%>

app/views/users/index.html.erb
<table class="table table-condensed">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
  </tr>
  <% @user.each do |user|%>
    <tr>
      <td><%= user.name%></td>
      <td><%= user.email%></td>
      <td><%= user.phone%></td>
      <td><%= link_to "Edit",edit_user_path(user), :class=>'btn btn-primary'%></td>
      <td><%= link_to "Delete",user,method: :delete, data: {confirm:"Are you sure?"}, :class=>'btn btn-danger'%></td>
      <td><%=link_to "Show",user_path(user),:class=>'btn btn-primary' %></td>
    </tr>
    <%end%>
  </table>
<%= link_to "Add User", new_user_path, :class=>'btn btn-primary'%>

app/views/users/login.html.erb
<%= form_tag action: :"validate_login",method: :post do%>
<table class='table table-striped'>
    <td><%= label_tag :email%></td>
    <td><%= email_field_tag :email%></td>
  </tr>
  <tr>
    <td><%= label_tag :password%></td>
    <td><%= password_field_tag :password%></td>
  </tr>
  <td><%= submit_tag "Sign in"%></td>

</table>
<%end%>

app/views/users/new.html.erb
<%= render "errors"%>

<%= form_for @user do | f |%>
<table class='table table-striped'>
  <tr>
    <td><%= f.label :name%></td>
    <td><%= f.text_field :name%></td>
  </tr>
  <tr>
    <td><%= f.label :email%></td>
    <td><%= f.email_field :email%></td>
  </tr>
  <tr>
    <td><%= f.label :password%></td>
    <td><%= f.password_field :password%></td>
  </tr>
  <tr>
    <td><%= f.label :confirm_password%></td>
    <td><%= f.password_field :confirm_password%></td>
  </tr>
  <tr>
    <td><%= f.label :phone%></td>
    <td><%= f.text_field :phone%></td>
  </tr>
  <td><%= f.submit%></td>

</table>
<%end%>
<%= link_to "Go Back", users_path, :class=>'btn btn-primary'%>

app/views/users/show.html.erb
<table class="table table-condensed">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
  </tr>
    <tr>
      <td><%= @user.name%></td>
      <td><%= @user.email%></td>
      <td><%= @user.phone%></td>
      <td><%= link_to "Edit",edit_user_path(@user), :class=>'btn btn-primary'%></td>
      <td><%= link_to "Delete",@user,method: :delete, data: {confirm:"Are you sure?"}, :class=>'btn btn-danger'%></td>
      <td><%=link_to "Show",user_path(@user),:class=>'btn btn-primary' %></td>
    </tr>
  </table>
<%= link_to "Add User", new_user_path, :class=>'btn btn-primary'%>
<%= link_to "Go Back", users_path,:class=>'btn btn-primary'%>